name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Android signing key
      run: |
        cd Launcher
        sed -i 's/C:\\\\Users\\\\Username\\\\/..\//g' build.gradle
        echo "${{ secrets.API_KEY }}" > android_signing_key.jks
    - name: Grant execute permission for gradlew
      run: |
        cd Launcher
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd Launcher
        ./gradlew build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: piLauncherNext-DEBUG.apk
        path: Launcher/App/build/outputs/apk/debug/App-debug.apk
