name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Create Android signing key from secret
      run: |
        cd Launcher
        sed -i 's/C:\\\\Users\\\\Username\\\\/..\//g' build.gradle
        echo -n "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 --decode > android_signing_key.jks
    - name: Grant execute permission for gradlew
      run: |
        cd Launcher
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd Launcher
        ./gradlew assembleRelease
    - name: Rename output
      run: |
        cd Launcher/App/build/outputs/apk/release
        mv App-release.apk piLauncherNext.apk
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: piLauncherNext
        path: Launcher/App/build/outputs/apk/debug/piLauncherNext.apk
